name: gp-molformer
channels:
    - conda-forge
    - nvidia
    - pytorch
    - rdkit
dependencies:
    - accelerate=0.26.1
    - datasets=2.20.0
    - networkx=3.1
    - numpy=1.24.3
    - pandas=2.2.3
    - peft=0.10.0
    - python=3.10
    - pytorch=2.1.0
    - pytorch-cuda=11.8
    - rdkit=2022.03.2
    - scikit-learn=1.5.1
    - transformers=4.32.1
